### ISSUE TITLE
Documentation problem in PascalCase function

### ISSUE THREAD

**Issue by xredo** [jmlweb/ramdu#9]
**Describe the bug**

A small error in the documentation of the library in the PascalCase function.

Check the example section in:

https://github.com/jmlweb/ramdu/blob/187384573f83d1229da02e609a5591d449ad2cc6/src/pascalCase.js#L5-L15

**Expected behavior**

```ts
/**
 * Transform a string to PascalCase
 *
 * @function
 * @param {String} str - Received string
 * @returns {String}
 *
 * @example
 * pascalCase('My name is Earl'); //'MyNameIsEarl'
 * pascalCase('my-name-is-earl'); //'MyNameIsEarl'
 */
```

**Comment by jmlweb** [comment]
Thanks!
